name: Test

on:
  push:
    branches: [main, feat/marketplace-integrations]
    paths:
      - 'devstudio_mcp/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/**'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen --all-extras

      - name: Verify package can be built
        run: uv build

      - name: Test uvx installation
        run: |
          WHL_FILE=$(ls dist/*.whl | head -n 1)
          uvx --from "$WHL_FILE" devstudio-mcp --help
        shell: bash
